version: '3'

services:

  # https://hub.docker.com/r/mysql/mysql-server/
  db:
    image: mysql/mysql-server:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./db-datadir:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  web:
    build: .
    command: sh -c "sleep 3; ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  selenium-hub:
    image: selenium/hub
    container_name: 'selenium-hub'
    ports:
      - 4444:4444

  chrome:
    image: selenium/node-chrome
    ports:
        - 9515:9515
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub   # 各自の環境に合わせて書き換えること
      - HUB_PORT_4444_TCP_PORT=4444  # 各自の環境に合わせて書き換えること
    depends_on:
      - selenium-hub
