# Generated by Django 2.0.3 on 2018-06-27 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('n_kyokiword', models.CharField(default='a', max_length=255, verbose_name='タイトル')),
                ('n_example', models.CharField(default='b', max_length=255, verbose_name='タイトル')),
                ('n_url', models.URLField(default='URLを入力して下さい', verbose_name='URL')),
                ('v_kyokiword', models.CharField(default='c', max_length=255, verbose_name='タイトル')),
                ('v_example', models.CharField(default='d', max_length=255, verbose_name='タイトル')),
                ('v_url', models.URLField(default='URLを入力して下さい', verbose_name='URL')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
            ],
        ),
    ]
